### ISSUE TITLE
Do some syntax highlighting

### ISSUE THREAD

**Issue by IngwiePhoenix** [jakiestfu/Behave.js#25]
I'd like to use Behave.js within a self-cooked Markdown editor, but I'd like to add syntax highlighting. Would there be a possibility to do this?

Kind regards, Ingwie.

**Comment by jakiestfu** [comment]
Behave is not meant to be used for syntax highlighting, only plain text. You should check out Ace Editor or Codemirror editors if you'd like more functionality like this

**Comment by IngwiePhoenix** [comment]
Problem is that the both are like 4x bigger than my Javascript stuff combined o.o But thank you anyway! :)
