### ISSUE TITLE
Add git tags

### ISSUE THREAD

**Issue by pvnr0082t** [jakiestfu/Behave.js#29]
Hi @jakiestfu,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we're going to host this library.
The git auto-updater in cdnjs relies on **[git tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging)** so that it can recognize the correct version and automatically update the repo. 
Could you please add git tags for the repo? Thank you.

https://github.com/cdnjs/cdnjs/issues/9411

**Comment by PeterDaveHello** [comment]
Hello @jakiestfu, would you like to take a look at this issue? Thanks!

**Comment by jakiestfu** [comment]
Added `1.5.0` and also published on `npm` 😬

**Comment by PeterDaveHello** [comment]
Thanks @jakiestfu
